### ISSUE TITLE
ABungeeAuth Console Error PaperSpigot 1.7.10 [aSpigot]

### ISSUE THREAD

**Issue by zRH-PvP** [leonardo-dgs/ABungeeAuth#4]
`27.03 16:23:12 [Server] INFO [ABungeeAuth] Enabling ABungeeAuth v1.4.4
27.03 16:23:12 [Server] ERROR Error occurred while enabling ABungeeAuth v1.4.4 (Is it up to date?)
27.03 16:23:12 [Server] INFO java.lang.NoClassDefFoundError: com/google/gson/JsonElement
27.03 16:23:12 [Server] INFO at net.leonardo_dgs.abungeeauth.bukkit.BukkitABungeeAuth.onEnable(Unknown Source) ~[?:?]
27.03 16:23:12 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[aSpigot.jar:git-PaperSpigot-ba75d9a]
27.03 16:23:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [aSpigot.jar:git-PaperSpigot-ba75d9a]
27.03 16:23:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [aSpigot.jar:git-PaperSpigot-ba75d9a]
27.03 16:23:12 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:478) [aSpigot.jar:git-PaperSpigot-ba75d9a]
27.03 16:23:12 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:396) [aSpigot.jar:git-PaperSpigot-ba75d9a]
27.03 16:23:12 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:346) [aSpigot.jar:git-PaperSpigot-ba75d9a]
27.03 16:23:12 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:320) [aSpigot.jar:git-PaperSpigot-ba75d9a]
27.03 16:23:12 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:276) [aSpigot.jar:git-PaperSpigot-ba75d9a]
27.03 16:23:12 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:227) [aSpigot.jar:git-PaperSpigot-ba75d9a]
27.03 16:23:12 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:486) [aSpigot.jar:git-PaperSpigot-ba75d9a]
27.03 16:23:12 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [aSpigot.jar:git-PaperSpigot-ba75d9a]
27.03 16:23:12 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonElement
27.03 16:23:12 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
27.03 16:23:12 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[aSpigot.jar:git-PaperSpigot-ba75d9a]
27.03 16:23:12 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[aSpigot.jar:git-PaperSpigot-ba75d9a]
27.03 16:23:12 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
27.03 16:23:12 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
27.03 16:23:12 [Server] INFO ... 12 more`

**Comment by dringewald** [comment]
As far as I know you need to install the Plug-In as a BungeeCore-Plug-In and not as a Spigot-Plugin.

**Comment by zRH-PvP** [comment]
### **Installation**

1. Put plugin jar file in the plugins folder of your BungeeCord
2. Set the plugin permissions on BungeeCord
3. Run your BungeeCord
4. Configure settings in the config.yml
5. Restart your BungeeCord
6. **Put plugin jar file in the plugins folder of servers used for the authentication**
7. Start the servers
8. Configure server-side settings of the plugin in the config.yml
9. Restart the servers
